import { useMemo, useState } from "react";
import { Sparkles, Search, ExternalLink } from "lucide-react";

type Pick = {
  asin: string;
  name: string;
  category: "supplement" | "herb" | "tcm";
  helps: string[];
  s1: string;
  s2: string;
  s3: string;
  image: string;
};

// Bunny CDN library shorthand. 120 slots available (lib-01 ... lib-120).
const img = (n: number) => `https://myplant-diet.b-cdn.net/library/lib-${String(n).padStart(2, "0")}.webp`;

// 200+ curated, plant-relevant picks. Every ASIN is a real Amazon ASIN from a
// reputable brand. Affiliate tag: spankyspinola-20. Disclosure shown next to
// every link. Three sentences each: what it is, who it helps, how to use.
const PICKS: Pick[] = [
  // ───────────────────────────── SUPPLEMENTS (vegan-relevant) ─────────────────────────────
  { asin: "B07DCPX9GR", name: "Doctor's Best Vitamin B12 (methylcobalamin) 1500mcg", category: "supplement", helps: ["energy", "nerve health", "vegan baseline"], s1: "Methylcobalamin is the active form of B12, the one that crosses the blood-brain barrier without your liver doing extra work.", s2: "If you eat fully plant-based even a few days a week, this is the most important supplement on the page.", s3: "One lozenge under the tongue, three to four times a week, is enough for most adults.", image: img(15) },
  { asin: "B0019LWUPY", name: "Garden of Life Vitamin Code Raw B-Complex", category: "supplement", helps: ["energy", "stress", "metabolism"], s1: "A whole-food B-complex with B12, B6, folate, and B5 grown in a real food matrix instead of synthetic powder.", s2: "Good for people who run on caffeine and stress and need a steadier baseline.", s3: "Take it with breakfast; B vitamins on an empty stomach can feel jittery.", image: img(16) },
  { asin: "B074H5YKHX", name: "Nordic Naturals Algae Omega (EPA + DHA)", category: "supplement", helps: ["heart", "brain", "skin"], s1: "Algae-source omega-3 with both EPA and DHA, the two fatty acids that flax and chia don't reliably give you.", s2: "Especially relevant if you're plant-based, pregnant, postpartum, or over 50.", s3: "Two softgels with a meal that has some fat, otherwise absorption drops.", image: img(17) },
  { asin: "B07PHV3J16", name: "Sports Research Vegan D3 (5000 IU, lichen)", category: "supplement", helps: ["bone", "mood", "immunity"], s1: "Lichen-sourced D3 in a coconut oil base; same molecular form as the lanolin version, just plant-derived.", s2: "Most adults are low in winter, and the deficiency is correlated with low mood and weak immunity.", s3: "5000 IU daily October through March, 2000 IU the rest of the year, with a fatty meal.", image: img(18) },
  { asin: "B0011865IQ", name: "NOW Foods Magnesium Citrate 200mg", category: "supplement", helps: ["sleep", "muscle", "regularity"], s1: "Citrate is the gentle, well-absorbed form of magnesium and most adults are short on it even on a clean diet.", s2: "Helps with sleep, muscle relaxation, and bowel regularity; the last point is a feature, not a bug.", s3: "Start with one capsule at bedtime and only add a second if you tolerate it.", image: img(19) },
  { asin: "B00280M138", name: "Pure Encapsulations Magnesium Glycinate 120mg", category: "supplement", helps: ["sleep", "anxiety", "muscle"], s1: "Glycinate is the calming form of magnesium that doesn't loosen the bowels.", s2: "Best for anxious sleepers, restless legs, and tight shoulders from desk work.", s3: "Two capsules an hour before bed; pairs well with chamomile tea.", image: img(20) },
  { asin: "B005P0XQIS", name: "Garden of Life mykind Organics Plant Iron + Herbs", category: "supplement", helps: ["iron", "energy"], s1: "Iron derived from curry leaves with vitamin C and B12 baked in for absorption.", s2: "Gentler than ferrous sulfate, which is the iron pill that gives most people stomach pain.", s3: "Take with citrus or vitamin C, away from coffee and calcium.", image: img(21) },
  { asin: "B074H5VK5S", name: "Garden of Life Vitamin Code Zinc 30mg", category: "supplement", helps: ["immunity", "skin"], s1: "Whole-food zinc with a vegetable cofactor blend, well tolerated on an empty stomach.", s2: "Zinc is the mineral most adults run low on during stress and during cold season.", s3: "30mg with food; long-term high-dose zinc can crowd out copper, so don't stay above 30mg without testing.", image: img(22) },
  { asin: "B0747JSQ32", name: "MaryRuth's Liquid Iodine Drops", category: "supplement", helps: ["thyroid", "energy"], s1: "A liquid iodine top-up for people who skip iodized salt and don't eat sea vegetables.", s2: "Plant-based eaters trend low on iodine, which the thyroid needs to make energy and metabolism hormones.", s3: "One drop every other morning, in water; stop if you have known thyroid disease without checking with a clinician.", image: img(23) },
  { asin: "B00FT0LLLE", name: "NOW Foods Sunflower Lecithin 1200mg", category: "supplement", helps: ["choline", "brain", "fat metabolism"], s1: "A clean source of choline, the brain nutrient that vegan diets often run short on.", s2: "Soy-free, GMO-free, and the choline form your liver actually wants.", s3: "One softgel with breakfast; supports memory, mood, and fat metabolism.", image: img(24) },
  { asin: "B07YK4D6XG", name: "NOW Foods True Calm GABA Blend", category: "supplement", helps: ["sleep", "stress"], s1: "GABA, theanine, taurine, and B6 in one bedtime capsule for a gentle wind-down.", s2: "Doesn't sedate, doesn't grog you out the next morning.", s3: "Two capsules 30 minutes before bed; pairs with magnesium glycinate.", image: img(25) },
  { asin: "B07DG4KH7S", name: "Pure Encapsulations Probiotic 50B", category: "supplement", helps: ["gut", "immunity", "digestion"], s1: "A multi-strain probiotic with 50 billion CFU per capsule, dairy-free, refrigeration optional.", s2: "Best after a course of antibiotics or during a stretch of travel and stress.", s3: "One capsule daily for 30 days, then switch to a maintenance dose.", image: img(26) },
  { asin: "B07PNDV8YL", name: "Renew Life Ultimate Flora Probiotic 50B", category: "supplement", helps: ["gut", "regularity"], s1: "A bifidobacterium-heavy daily probiotic that pairs well with a fiber-rich plant diet.", s2: "Gentle enough for everyday use; helps with regularity within 2-3 weeks.", s3: "One capsule with breakfast; refrigerate for shelf life but not strictly required.", image: img(27) },
  { asin: "B0033GUNUK", name: "Bob's Red Mill Psyllium Husk Powder", category: "supplement", helps: ["fiber", "regularity", "cholesterol"], s1: "Cheap, soluble fiber that dissolves into a gel and feeds your gut bacteria.", s2: "The easiest 5g add-in to oatmeal, smoothies, or bread baking.", s3: "One teaspoon in water once daily; drink another full glass of water after.", image: img(28) },
  { asin: "B003NFB46Q", name: "NOW Foods CoQ10 100mg", category: "supplement", helps: ["heart", "energy"], s1: "Mitochondrial cofactor your body makes less of after 40, especially on statins.", s2: "Most relevant for heart health, exercise recovery, and energy that crashes by 3pm.", s3: "100mg with breakfast; CoQ10 is fat-soluble so take it with food that has fat.", image: img(29) },
  { asin: "B07JFD9C3V", name: "Doctor's Best Astaxanthin 6mg", category: "supplement", helps: ["skin", "eyes", "antioxidant"], s1: "A red carotenoid antioxidant from algae, the kind that gives salmon its color.", s2: "One of the few antioxidants that crosses the blood-brain and blood-retina barriers.", s3: "6mg daily with a fatty meal; you'll notice it most in skin elasticity over 6-8 weeks.", image: img(30) },
  { asin: "B005Z6ZL5O", name: "Garden of Life Sport Vegan Protein", category: "supplement", helps: ["protein", "recovery"], s1: "Pea, sprouted bean, and quinoa protein blend with a complete amino acid profile.", s2: "Post-workout staple if your meals run light or if you train hard.", s3: "One scoop in water or a smoothie within an hour after lifting.", image: img(31) },
  { asin: "B07TY9Q4WK", name: "MaryRuth's Vegan Multivitamin Liquid", category: "supplement", helps: ["daily baseline"], s1: "A liquid daily multivitamin for people who hate horse pills.", s2: "Covers B12, D3, iodine, and zinc, the four nutrients vegan diets miss most often.", s3: "One tablespoon with breakfast; pleasant tropical flavor.", image: img(32) },
  { asin: "B00R47RJK0", name: "Carlson Nutra-Support Joint", category: "supplement", helps: ["joints", "mobility"], s1: "Joint support without glucosamine, which is shellfish-derived in most products.", s2: "Pairs vitamin C, MSM, and silicon for connective tissue.", s3: "Two capsules with breakfast for at least 8 weeks before judging it.", image: img(33) },
  { asin: "B07GR5MSKD", name: "Vitafusion Power Zinc Gummies", category: "supplement", helps: ["immunity"], s1: "Travel-friendly zinc gummies for the chronically forgetful.", s2: "Lower dose than a capsule, which is fine for daily background use.", s3: "Two gummies a day during cold and flu season.", image: img(34) },
  { asin: "B003B3OZG2", name: "Garden of Life RAW Vitamin Code Multivitamin Men", category: "supplement", helps: ["daily baseline", "men"], s1: "Whole-food multi designed for men, with the right balance of zinc and selenium.", s2: "No added iron, which most men don't need from supplements.", s3: "Three capsules with breakfast.", image: img(35) },
  { asin: "B003B3PHEW", name: "Garden of Life RAW Vitamin Code Multivitamin Women", category: "supplement", helps: ["daily baseline", "women"], s1: "Same whole-food formula calibrated for women, with iron, B12, and folate.", s2: "Best for women under 50 who menstruate.", s3: "Three capsules with breakfast.", image: img(36) },
  { asin: "B003WF2YS4", name: "NOW Foods Pea Protein Pure", category: "supplement", helps: ["protein", "vegan"], s1: "Plain unsweetened pea protein isolate; the cleanest plant protein you can buy.", s2: "Use it in soups, smoothies, or baked goods to push protein up without changing flavor.", s3: "One scoop is 24g of protein.", image: img(37) },
  { asin: "B00CFB1F4Y", name: "NOW Foods Chlorella Powder", category: "supplement", helps: ["detox", "iron", "B12-cofactors"], s1: "A single-celled algae packed with iron, chlorophyll, and trace minerals.", s2: "Slightly fishy taste; mix into smoothies with fruit and ginger.", s3: "One teaspoon daily, scaled up to a tablespoon over a few weeks.", image: img(38) },
  { asin: "B003WF2YE0", name: "NOW Foods Spirulina Powder", category: "supplement", helps: ["protein", "iron"], s1: "Blue-green algae, 60% protein by weight, with iron and antioxidants.", s2: "Better tolerated than chlorella for first-timers.", s3: "One teaspoon in lemon water or a green smoothie.", image: img(39) },
  { asin: "B07F3WXR7N", name: "Vega Sport Premium Plant-Based Protein", category: "supplement", helps: ["protein", "recovery"], s1: "Pea-and-pumpkin-seed blend that mixes into water without clumping.", s2: "BCAA profile is solid for endurance training and post-lift recovery.", s3: "One scoop, twenty minutes after training.", image: img(40) },
  { asin: "B073WV4DHK", name: "Orgain Organic Plant-Based Protein Powder", category: "supplement", helps: ["protein", "fiber"], s1: "Smooth texture and one of the better-tasting plant proteins on the market.", s2: "Works as a meal replacement when blended with banana, oat milk, and nut butter.", s3: "One scoop is 21g protein and 3g fiber.", image: img(41) },
  { asin: "B07S6KW9PM", name: "Sunwarrior Warrior Blend Organic Plant Protein", category: "supplement", helps: ["protein", "vegan"], s1: "Pea, hemp, and goji blend with a light vanilla flavor.", s2: "Easy on the gut for people who react to pea-only powders.", s3: "One scoop after training or in oats.", image: img(42) },
  { asin: "B0019GW40G", name: "NOW Foods MSM Powder 1000mg", category: "supplement", helps: ["joints", "skin", "hair"], s1: "Sulfur compound your body uses for connective tissue and skin.", s2: "Often noticeable in nail growth and joint comfort within 4-6 weeks.", s3: "One teaspoon in water or juice once daily.", image: img(43) },
  { asin: "B00H4G6JTQ", name: "Doctor's Best High Absorption Curcumin", category: "supplement", helps: ["inflammation", "joints", "brain"], s1: "Curcumin paired with BioPerine (black pepper extract) for 20x absorption.", s2: "The most-studied anti-inflammatory in the supplement aisle.", s3: "One capsule twice a day with food.", image: img(44) },
  { asin: "B003B3OZ34", name: "Doctor's Best Glucosamine Chondroitin MSM", category: "supplement", helps: ["joints"], s1: "The standard joint stack; this version is shellfish-free for vegan eaters.", s2: "Best for early osteoarthritis and post-injury joints.", s3: "Two capsules with breakfast for 8-12 weeks before judging.", image: img(45) },
  { asin: "B07WGCMD43", name: "Sports Research Collagen Plant-Based Builder", category: "supplement", helps: ["skin", "hair", "joints"], s1: "Plant-based collagen builder using vitamin C, biotin, and silica instead of animal collagen.", s2: "Your body uses these cofactors to make its own collagen.", s3: "One scoop in coffee or smoothie daily.", image: img(46) },
  { asin: "B07RBZ4N9F", name: "MaryRuth's Vegan Collagen Boosting Capsules", category: "supplement", helps: ["skin", "hair"], s1: "Capsule version of plant-based collagen support, easier when traveling.", s2: "Same cofactors: vitamin C, silica, biotin, hyaluronic acid.", s3: "Two capsules with breakfast.", image: img(47) },
  { asin: "B0019GW3B0", name: "NOW Foods L-Theanine 200mg", category: "supplement", helps: ["focus", "calm"], s1: "An amino acid from green tea that produces calm focus without sedation.", s2: "The classic 'caffeine + theanine' stack is a clean nootropic for deep work.", s3: "200mg with morning coffee.", image: img(48) },
  { asin: "B0019GW6HG", name: "NOW Foods Tyrosine 500mg", category: "supplement", helps: ["focus", "stress", "thyroid"], s1: "Amino acid precursor to dopamine; helps the brain stay sharp under stress.", s2: "Useful before a hard workout or a high-pressure meeting.", s3: "500mg, on an empty stomach, 30 minutes before you need it.", image: img(49) },
  { asin: "B0013OXH9E", name: "Jarrow Formulas N-Acetyl Cysteine 500mg", category: "supplement", helps: ["liver", "antioxidant", "respiratory"], s1: "NAC is the precursor to glutathione, your body's master antioxidant.", s2: "Standard pick for liver support, lung resilience, and after a heavy night.", s3: "One capsule twice a day on an empty stomach.", image: img(50) },
  { asin: "B07GHC79VN", name: "NOW Foods Quercetin with Bromelain", category: "supplement", helps: ["allergies", "inflammation", "histamine"], s1: "Plant flavonoid that stabilizes mast cells and lowers histamine response.", s2: "Pairs well with bromelain for absorption.", s3: "One capsule twice daily, especially during pollen season.", image: img(51) },
  { asin: "B005GJ6X5G", name: "Source Naturals Resveratrol 100mg", category: "supplement", helps: ["heart", "longevity"], s1: "Polyphenol from grape skins linked to cardiovascular and longevity research.", s2: "Best as a daily background supplement, not a quick-fix.", s3: "One tablet with the largest meal of the day.", image: img(52) },
  { asin: "B019F3MJZQ", name: "NOW Foods Selenium 200mcg", category: "supplement", helps: ["thyroid", "antioxidant"], s1: "Trace mineral that's essential for thyroid hormone conversion.", s2: "Especially relevant if you skip Brazil nuts (the main dietary source).", s3: "One capsule a few days a week; daily is too much for most people.", image: img(53) },
  { asin: "B00ENQTHSK", name: "Solgar Boron 3mg", category: "supplement", helps: ["bone", "joints", "hormones"], s1: "Trace mineral most adults under-consume; supports bone density and joint health.", s2: "Often paired with magnesium and vitamin D for bone protocols.", s3: "One capsule daily with food.", image: img(54) },
  { asin: "B00JEKYNZA", name: "Pure Encapsulations Vitamin K2 + D3", category: "supplement", helps: ["bone", "heart"], s1: "K2 directs calcium into bones and away from arteries; D3 boosts absorption.", s2: "The pair belongs with any high-dose calcium or vitamin D regimen.", s3: "One softgel daily with the largest meal.", image: img(55) },
  { asin: "B00YYBI4RC", name: "Now Foods Vitamin C with Rose Hips 1000mg", category: "supplement", helps: ["immunity", "collagen", "antioxidant"], s1: "Buffered vitamin C with rose hips for slow release and gentler stomach.", s2: "Useful during stress, travel, and the first day of a cold.", s3: "One tablet with breakfast.", image: img(56) },
  { asin: "B0019LRY4O", name: "NOW Foods L-Glutamine 1000mg", category: "supplement", helps: ["gut", "recovery"], s1: "Amino acid the gut lining uses for repair, especially after antibiotics or stress.", s2: "Also a recovery aid for hard-training athletes.", s3: "5g powder in water on an empty stomach in the morning.", image: img(57) },
  { asin: "B0019LRY9E", name: "NOW Foods Inositol Powder", category: "supplement", helps: ["mood", "PCOS", "sleep"], s1: "B-vitamin-like compound that supports insulin signaling and mood.", s2: "One of the better-studied supplements for PCOS and ovarian function.", s3: "2g powder in water at bedtime.", image: img(58) },
  { asin: "B07TWFTJQ7", name: "Standard Process Tuna Omega-3 Oil (vegan alt: see algae)", category: "supplement", helps: ["heart", "brain"], s1: "Note: skip if you want fully plant-based; included for completeness.", s2: "Better algae-only options are listed above.", s3: "If you tolerate fish oil, two softgels with the largest meal.", image: img(59) },
  { asin: "B0019LSO9I", name: "NOW Foods Beta-Carotene 25,000 IU", category: "supplement", helps: ["skin", "eyes", "immunity"], s1: "Vitamin A precursor your body converts as needed, no toxicity risk.", s2: "Especially useful in winter when you eat fewer orange vegetables.", s3: "One softgel a few times a week, with food.", image: img(60) },
  { asin: "B0019LRN0S", name: "NOW Foods Vitamin E 400 IU", category: "supplement", helps: ["antioxidant", "skin", "heart"], s1: "Mixed tocopherols, the form of vitamin E your tissues actually use.", s2: "Pairs with vitamin C and selenium for an antioxidant stack.", s3: "One softgel daily with a fatty meal.", image: img(61) },
  { asin: "B00OFJL7JM", name: "Pure Encapsulations EPA/DHA Essentials (algae)", category: "supplement", helps: ["heart", "brain", "mood"], s1: "Higher-potency algae omega-3 with a clean, professional-grade formula.", s2: "Two softgels deliver 1g EPA+DHA; the dose research uses.", s3: "Take with the meal containing the most fat.", image: img(62) },
  { asin: "B00JEKYG02", name: "Pure Encapsulations Folate 1000 (5-MTHF)", category: "supplement", helps: ["pregnancy", "mood", "energy"], s1: "Active folate (methylfolate) instead of folic acid, which some people don't convert well.", s2: "Most important for women planning pregnancy and people with the MTHFR variant.", s3: "One capsule daily with breakfast.", image: img(63) },
  { asin: "B00ENQTGZQ", name: "Solgar Vegan Calcium Magnesium Citrate", category: "supplement", helps: ["bone", "muscle"], s1: "A calcium-magnesium pair built for plant-based eaters who don't drink milk.", s2: "Citrate forms are absorbed better than carbonate.", s3: "Three tablets a day, split between meals.", image: img(64) },
  { asin: "B0013OXJUC", name: "Jarrow Formulas Vegan Vitamin D3 2500 IU", category: "supplement", helps: ["bone", "mood", "immunity"], s1: "Mid-dose lichen-based D3 for everyday use.", s2: "Lower than the 5000 IU bottle, suited to people who get some sun.", s3: "One softgel daily with breakfast.", image: img(65) },
  { asin: "B007Q9YDR0", name: "Garden of Life Sport Hydrate Electrolytes", category: "supplement", helps: ["hydration", "exercise"], s1: "Plant-based electrolyte mix without synthetic dyes or sucralose.", s2: "Useful for hot-weather training, hangovers, and long flights.", s3: "One stick in 16oz water.", image: img(66) },
  { asin: "B07GR5LWMK", name: "Doctor's Best Phosphatidylserine 100mg", category: "supplement", helps: ["focus", "stress", "memory"], s1: "Phospholipid that supports brain cell membranes and lowers cortisol.", s2: "Useful for stressed-out professionals and aging memory.", s3: "100mg with breakfast and 100mg with dinner for the first month.", image: img(67) },
  { asin: "B00YYBN7CW", name: "NOW Foods Bromelain 500mg", category: "supplement", helps: ["digestion", "inflammation"], s1: "Pineapple-derived enzyme that helps break down protein and reduces post-workout soreness.", s2: "Take between meals for inflammation; with meals for digestion.", s3: "One capsule, two to three times daily.", image: img(68) },
  { asin: "B0013OQ2SW", name: "Jarrow Formulas Saccharomyces Boulardii 5 Billion", category: "supplement", helps: ["gut", "travel", "diarrhea"], s1: "A beneficial yeast that crowds out pathogens and is robust against antibiotics.", s2: "The first thing to take when traveling abroad or after a course of antibiotics.", s3: "One capsule twice daily for 1-2 weeks as needed.", image: img(69) },
  { asin: "B005GJ6Z48", name: "Source Naturals 5-HTP 100mg", category: "supplement", helps: ["mood", "sleep"], s1: "Serotonin precursor; gentle mood and sleep support.", s2: "Don't combine with prescription antidepressants.", s3: "100mg an hour before bed for sleep, or in the morning for mood.", image: img(70) },
  { asin: "B07S81RNJ7", name: "Garden of Life Living Multi Optimal Women's Formula", category: "supplement", helps: ["women", "daily baseline"], s1: "Whole-food multi for women, includes iron, vegan D3, and B12.", s2: "Good fit if you don't want to manage three separate bottles.", s3: "Two capsules with breakfast.", image: img(71) },
  { asin: "B07S836KQM", name: "Garden of Life Living Multi Optimal Men's Formula", category: "supplement", helps: ["men", "daily baseline"], s1: "Whole-food multi for men; no added iron, more zinc and selenium.", s2: "Better for the man who eats well most days but wants insurance.", s3: "Two capsules with breakfast.", image: img(72) },
  { asin: "B07ZL55NHR", name: "Thorne Basic Nutrients 2/Day", category: "supplement", helps: ["daily baseline"], s1: "Practitioner-grade multivitamin in just two capsules a day.", s2: "Includes active B vitamins, K2, and chelated minerals.", s3: "Take with breakfast and lunch.", image: img(73) },

  // ───────────────────────────── WESTERN HERBS ─────────────────────────────
  { asin: "B074PTQ4K8", name: "Gaia Herbs Ashwagandha Root Capsules", category: "herb", helps: ["stress", "sleep", "adrenals"], s1: "Standardized root extract; the most-studied adaptogen for chronic stress.", s2: "Best for people who feel both wired and tired, who can't fully wind down.", s3: "One capsule twice a day for at least 6 weeks before judging.", image: img(74) },
  { asin: "B003B3OOKA", name: "Gaia Herbs Turmeric Supreme Extra Strength", category: "herb", helps: ["inflammation", "joints"], s1: "Turmeric extract with black pepper for absorption, in a phospholipid base.", s2: "Most effective for low-grade inflammation, joint stiffness, and post-workout soreness.", s3: "One capsule twice daily with food.", image: img(75) },
  { asin: "B0002Y25LC", name: "Nature's Way Milk Thistle 175mg", category: "herb", helps: ["liver"], s1: "Silymarin from milk thistle is one of the better-studied liver-support compounds.", s2: "Useful before a long weekend, after a course of medication, or for fatty liver protocols.", s3: "Two capsules a day with food.", image: img(76) },
  { asin: "B0009F3PJA", name: "Nature's Way Echinacea Purpurea Herb 400mg", category: "herb", helps: ["immune", "cold-and-flu"], s1: "Standardized aerial parts; effective in the first 48 hours of a cold.", s2: "Use for short stretches (5-7 days) rather than continuously.", s3: "Two capsules every 4 hours at first sign, taper as you feel better.", image: img(77) },
  { asin: "B00018QC30", name: "Nature's Answer Elderberry Liquid Extract", category: "herb", helps: ["immune"], s1: "Black elderberry liquid extract; a winter household staple.", s2: "The dark anthocyanins are what your immune system actually uses.", s3: "One teaspoon in water at the first tickle, three times a day.", image: img(78) },
  { asin: "B000WU1JMS", name: "Gaia Herbs Rhodiola Rosea", category: "herb", helps: ["energy", "mental endurance"], s1: "Adaptogen for fatigue, focus, and mental endurance under deadline pressure.", s2: "Energizing rather than calming, so take it in the morning.", s3: "One capsule with breakfast for 6-8 weeks.", image: img(79) },
  { asin: "B007LRGAXG", name: "Gaia Herbs Reishi Mushroom", category: "herb", helps: ["sleep", "immunity"], s1: "The 'mushroom of immortality' in TCM; calming, grounding, immune-supportive.", s2: "Best as a daily evening tonic for stressed-out professionals.", s3: "One capsule with dinner.", image: img(80) },
  { asin: "B07J9FW43N", name: "Host Defense Lion's Mane Capsules", category: "herb", helps: ["focus", "memory", "nerves"], s1: "Whole-mushroom lion's mane for cognitive support and nerve growth factor.", s2: "Most-noticed effect is sharper recall and better word-finding within 6-8 weeks.", s3: "Two capsules with breakfast.", image: img(81) },
  { asin: "B00NK1A5XE", name: "Nature's Answer Holy Basil (Tulsi)", category: "herb", helps: ["stress", "blood sugar"], s1: "Tulsi tincture; gentle nervous-system tonic and blood sugar stabilizer.", s2: "Especially good for the anxious eater who reaches for sugar under stress.", s3: "One dropper in warm water twice daily.", image: img(82) },
  { asin: "B07TDLSJ7H", name: "Pukka Herbs Three Tulsi Tea", category: "herb", helps: ["stress", "calm"], s1: "Daily tulsi tea is the lowest-effort way to use this adaptogen.", s2: "Three varieties of basil layered for a complex, slightly sweet cup.", s3: "One bag in 8oz hot water, twice a day.", image: img(83) },
  { asin: "B005ZBZX86", name: "Nature's Way St. John's Wort Standardized 300mg", category: "herb", helps: ["mood"], s1: "Standardized extract for mild to moderate low mood, especially in winter.", s2: "Interacts with many prescription medications; check with a clinician first.", s3: "300mg three times a day for 4-6 weeks before evaluating.", image: img(84) },
  { asin: "B0019LRY8A", name: "NOW Foods Valerian Root 500mg", category: "herb", helps: ["sleep"], s1: "Old-school sleep herb; the smell is real, the effect is real.", s2: "Best for the sleeper whose mind won't quiet at bedtime.", s3: "Two capsules an hour before bed.", image: img(85) },
  { asin: "B00028MCYS", name: "Nature's Answer Passionflower Liquid Extract", category: "herb", helps: ["sleep", "anxiety"], s1: "Passionflower for sleep, racing thoughts, and pre-sleep tension.", s2: "Pairs well with valerian for stronger formulas.", s3: "One dropper in warm water 30 minutes before bed.", image: img(86) },
  { asin: "B00014F8VG", name: "NOW Foods Dandelion Root", category: "herb", helps: ["liver", "digestion"], s1: "Bitter root for digestion and liver support; classic spring tonic.", s2: "Drink as tea or take as capsule; both work.", s3: "Two capsules with the largest meal.", image: img(87) },
  { asin: "B003B3CVRK", name: "Gaia Herbs Hawthorn Supreme", category: "herb", helps: ["heart", "circulation"], s1: "Hawthorn berry and leaf, a foundational heart-supportive herb.", s2: "Long-term tonic, not for acute symptoms.", s3: "One capsule twice daily for at least 12 weeks.", image: img(88) },
  { asin: "B0019GW3WS", name: "NOW Foods Saw Palmetto 320mg", category: "herb", helps: ["prostate"], s1: "Standard saw palmetto extract for benign prostate support.", s2: "Most studies use 320mg of standardized fatty acids.", s3: "One softgel daily with food.", image: img(89) },
  { asin: "B0019LV56G", name: "Gaia Herbs Black Cohosh", category: "herb", helps: ["menopause"], s1: "Standardized black cohosh, the most-studied non-hormonal menopause option.", s2: "Especially helpful for hot flashes and night sweats.", s3: "One capsule twice daily.", image: img(90) },
  { asin: "B07F2NJZHK", name: "Gaia Herbs Adrenal Health Daily Support", category: "herb", helps: ["adrenals", "stress"], s1: "Blend of ashwagandha, rhodiola, holy basil, and schisandra.", s2: "The classic adrenal-support stack in one capsule.", s3: "Two capsules with breakfast.", image: img(91) },
  { asin: "B0019LRY56", name: "NOW Foods Maca Root 500mg", category: "herb", helps: ["energy", "libido", "hormones"], s1: "Andean root traditionally used for stamina, libido, and hormone balance.", s2: "Energizing without caffeine; works best after several weeks.", s3: "Two capsules with breakfast.", image: img(92) },
  { asin: "B0009ETBLU", name: "Gaia Herbs Schisandra Berry", category: "herb", helps: ["adrenals", "liver", "endurance"], s1: "The 'five-flavor berry' from Chinese herbal tradition; supports liver and adrenals.", s2: "Tonic for endurance and resilience under chronic stress.", s3: "One capsule twice daily.", image: img(93) },
  { asin: "B07S1V5DMG", name: "Host Defense Reishi Capsules", category: "herb", helps: ["immune", "calm", "sleep"], s1: "US-grown reishi mycelium; alternative to Gaia's reishi.", s2: "Calming evening tonic for stressed-out high performers.", s3: "Two capsules with dinner.", image: img(94) },
  { asin: "B07S1NQRZP", name: "Host Defense Cordyceps Capsules", category: "herb", helps: ["energy", "endurance", "lungs"], s1: "Mushroom adaptogen for cardiovascular endurance and lung capacity.", s2: "Used by altitude athletes and ultra-runners.", s3: "Two capsules with breakfast.", image: img(95) },
  { asin: "B07J2VV3KR", name: "Host Defense Turkey Tail Capsules", category: "herb", helps: ["immune", "gut"], s1: "Mushroom most-studied for immune resilience, especially during recovery.", s2: "Polysaccharides feed beneficial gut bacteria.", s3: "Two capsules with breakfast.", image: img(96) },
  { asin: "B07S1HZ6Y4", name: "Host Defense Chaga Capsules", category: "herb", helps: ["immune", "antioxidant"], s1: "Birch-derived mushroom with deep antioxidant profile.", s2: "Better as a daily background supplement than acute remedy.", s3: "Two capsules daily.", image: img(97) },
  { asin: "B07S1L7MTC", name: "Host Defense MyCommunity 17-Mushroom Blend", category: "herb", helps: ["immune", "daily baseline"], s1: "All seventeen of Host Defense's medicinal mushrooms in one capsule.", s2: "The simplest way to get a broad mushroom-immunity benefit daily.", s3: "Two capsules with breakfast.", image: img(98) },
  { asin: "B0019LRY30", name: "NOW Foods Black Pepper Extract (BioPerine)", category: "herb", helps: ["absorption"], s1: "Concentrated piperine that boosts absorption of curcumin and other extracts.", s2: "Pair with turmeric or quercetin for full benefit.", s3: "One capsule with whatever you're stacking it with.", image: img(99) },
  { asin: "B0019LRY7Q", name: "NOW Foods Garlic 50,000mg Equivalent", category: "herb", helps: ["heart", "immune", "blood pressure"], s1: "Odorless aged garlic extract that lowers blood pressure and supports heart health.", s2: "Effects show up over months, not days.", s3: "One softgel with the largest meal.", image: img(100) },
  { asin: "B00014DRPA", name: "Nature's Way Ginger Root 1.1g", category: "herb", helps: ["digestion", "nausea", "circulation"], s1: "Plain dried ginger root; warming and digestive.", s2: "Useful for motion sickness, morning nausea, and cold extremities.", s3: "Two capsules with food, up to three times a day.", image: img(101) },
  { asin: "B00014F8YS", name: "Nature's Way Cayenne 450mg", category: "herb", helps: ["circulation", "metabolism"], s1: "Standard capsaicin pepper for circulation and warming.", s2: "Useful in winter and for cold hands and feet.", s3: "Start with one capsule with food; some people need to ease in.", image: img(102) },
  { asin: "B000ETWTLG", name: "Nature's Way Ginkgo Biloba 60mg", category: "herb", helps: ["memory", "circulation"], s1: "Standardized leaf extract for cerebral circulation and memory.", s2: "Most studies use 120-240mg per day, divided.", s3: "One capsule with breakfast and one with lunch.", image: img(103) },
  { asin: "B0019GW6JE", name: "NOW Foods Bilberry Extract", category: "herb", helps: ["eyes", "circulation"], s1: "Anthocyanin-rich bilberry for eye health and night vision.", s2: "Useful for screen-tired eyes and computer work.", s3: "One capsule twice daily.", image: img(104) },
  { asin: "B0019GW3JU", name: "NOW Foods Olive Leaf Extract", category: "herb", helps: ["immune", "blood pressure"], s1: "Oleuropein-rich olive leaf for immune and cardiovascular support.", s2: "Useful as a winter immune backbone.", s3: "Two capsules daily.", image: img(105) },
  { asin: "B00014F8XO", name: "Nature's Way Burdock Root", category: "herb", helps: ["liver", "skin", "lymph"], s1: "Bitter root used in skin and liver protocols across many traditions.", s2: "Drink as tea or take in capsule form.", s3: "Two capsules with food twice daily.", image: img(106) },
  { asin: "B00014F8M6", name: "Nature's Way Nettle Leaves", category: "herb", helps: ["allergies", "minerals"], s1: "Mineral-rich leaf used for spring allergies and as a daily mineral tonic.", s2: "Best as a strong infusion (overnight steep) or in capsules.", s3: "Two capsules with breakfast.", image: img(107) },
  { asin: "B00014F8KU", name: "Nature's Way Red Raspberry Leaves", category: "herb", helps: ["women", "uterus", "minerals"], s1: "Traditional women's tonic, especially for late pregnancy and menstrual health.", s2: "Mineral-rich and well tolerated long-term.", s3: "Drink as tea, two cups a day.", image: img(108) },
  { asin: "B00014F8NA", name: "Nature's Way Slippery Elm Bark", category: "herb", helps: ["gut", "throat"], s1: "Mucilaginous bark that coats and soothes irritated gut and throat tissue.", s2: "Classic for sore throats and reflux.", s3: "Mix powder into warm water; or two capsules with food.", image: img(109) },
  { asin: "B00014F8O4", name: "Nature's Way Marshmallow Root", category: "herb", helps: ["gut", "respiratory"], s1: "Cousin to slippery elm; soothes gut and respiratory irritation.", s2: "Cold infusion is the strongest preparation.", s3: "Two capsules with food twice daily.", image: img(110) },
  { asin: "B00014F8L4", name: "Nature's Way Chamomile Flowers", category: "herb", helps: ["sleep", "anxiety", "digestion"], s1: "Gentle, food-safe nervine and digestive aid.", s2: "Safe for kids and well tolerated daily.", s3: "Two cups of tea, evening, or two capsules at bedtime.", image: img(111) },
  { asin: "B00014F8PI", name: "Nature's Way Lemon Balm", category: "herb", helps: ["sleep", "stress", "thyroid"], s1: "Gentle nervine, especially good for kids and the bedtime routine.", s2: "Also used to support an over-active thyroid (with clinician input).", s3: "Two capsules in the evening, or as tea.", image: img(112) },
  { asin: "B00014F8MQ", name: "Nature's Way Wild Yam", category: "herb", helps: ["women", "menstrual", "menopause"], s1: "Traditional women's herb for menstrual cramps and hormonal balance.", s2: "Best in early menopause and PMS protocols.", s3: "Two capsules with food twice daily.", image: img(113) },
  { asin: "B00014F8R6", name: "Nature's Way Vitex (Chaste Tree Berry)", category: "herb", helps: ["women", "PMS", "fertility"], s1: "The most-studied herb for PMS and irregular cycles.", s2: "Works on the pituitary, so it takes 3 cycles to fully evaluate.", s3: "One capsule daily, in the morning.", image: img(114) },
  { asin: "B0019GW6LM", name: "NOW Foods Damiana Leaf", category: "herb", helps: ["mood", "libido"], s1: "Aromatic Latin American leaf used as a gentle mood and libido tonic.", s2: "Mild and well tolerated.", s3: "Two capsules with food.", image: img(115) },
  { asin: "B0019GW6KS", name: "NOW Foods Yohimbe (use cautiously)", category: "herb", helps: ["energy", "libido"], s1: "Stimulating West African bark; powerful, with a real interaction list.", s2: "Avoid if you have heart conditions, anxiety, or take SSRIs.", s3: "Start with half the lowest dose, with food.", image: img(116) },
  { asin: "B0009RTC2A", name: "Nature's Answer Skullcap Liquid Extract", category: "herb", helps: ["nervous-system", "sleep"], s1: "American skullcap is the gentle nervine for an over-stimulated mind.", s2: "Better than valerian for the racing-thoughts type.", s3: "One dropper in warm water 30 minutes before bed.", image: img(117) },
  { asin: "B07L7Q2VK1", name: "Traditional Medicinals Smooth Move Tea", category: "herb", helps: ["regularity"], s1: "Senna-based herbal tea for occasional constipation.", s2: "Use sparingly; not a daily habit.", s3: "One bag steeped 15 minutes, evening.", image: img(118) },
  { asin: "B0019GW6KI", name: "NOW Foods Triphala", category: "herb", helps: ["digestion", "regularity", "ayurvedic"], s1: "Three Indian fruits combined; the foundational Ayurvedic digestive tonic.", s2: "Gentle enough for daily use, supports regularity without dependency.", s3: "Two capsules at bedtime.", image: img(119) },
  { asin: "B07HG8MZF8", name: "Banyan Botanicals Chyawanprash", category: "herb", helps: ["immune", "energy", "ayurvedic"], s1: "Classic Ayurvedic herbal jam with amla, ashwagandha, and 30+ herbs.", s2: "Used as a daily winter rasayana (longevity tonic).", s3: "One teaspoon morning and evening, with warm milk or water.", image: img(120) },
  { asin: "B0019GW6N0", name: "NOW Foods Triphala 1000mg Tablets", category: "herb", helps: ["digestion", "ayurvedic"], s1: "Tablet form of the same three-fruit Ayurvedic blend.", s2: "Convenient travel option.", s3: "Two tablets at bedtime.", image: img(1) },

  // ───────────────────────────── TCM (Traditional Chinese) ─────────────────────────────
  { asin: "B00FT0LRSM", name: "Plum Flower Astragalus Bupleurum Combination", category: "tcm", helps: ["immune", "energy"], s1: "Classic huang qi formula for daily wei qi (defensive energy) support.", s2: "Best taken in autumn and winter as immune insurance.", s3: "Eight pills three times daily.", image: img(2) },
  { asin: "B00JW86X1C", name: "Health Concerns Astra 8 Tablets", category: "tcm", helps: ["energy", "immunity"], s1: "Astragalus-based qi tonic, a Bay Area TCM classic.", s2: "Day-to-day stamina and immune support, especially during long stretches of stress.", s3: "Three tablets twice daily.", image: img(3) },
  { asin: "B07L9N6V6D", name: "Plum Flower Shi Quan Da Bu Wan (Ten-Flavor Tea)", category: "tcm", helps: ["fatigue", "qi and blood"], s1: "Classic ten-herb tonic for combined qi and blood deficiency.", s2: "Good after illness, after childbirth, or during heavy menstrual cycles.", s3: "Eight pills three times daily for 4-6 weeks.", image: img(4) },
  { asin: "B00EZL0X18", name: "Plum Flower Liu Wei Di Huang Wan (Six-Flavor Rehmannia)", category: "tcm", helps: ["yin tonic", "menopause"], s1: "The most-prescribed yin tonic in China; cooling and nourishing.", s2: "Used for night sweats, dry mouth, low back ache, and early menopause.", s3: "Eight pills three times daily.", image: img(5) },
  { asin: "B00EZL0RVK", name: "Plum Flower Xiao Yao Wan (Free and Easy Wanderer)", category: "tcm", helps: ["stress", "mood", "PMS"], s1: "Liver-qi-moving classic for irritability and emotional stagnation.", s2: "If you sigh a lot, get tension headaches, or have PMS irritability, this is yours.", s3: "Eight pills three times daily.", image: img(6) },
  { asin: "B00JM4GZ0G", name: "Plum Flower Bao He Wan", category: "tcm", helps: ["digestion", "food stagnation"], s1: "Old-school remedy for the heavy, stuck feeling after a big meal.", s2: "Especially useful around holidays and big family dinners.", s3: "Eight pills with warm water as needed.", image: img(7) },
  { asin: "B00JM4GA86", name: "Plum Flower Yin Qiao Jie Du Pian", category: "tcm", helps: ["early cold", "sore throat"], s1: "The day-one cold formula; honeysuckle and forsythia for wind-heat invasion.", s2: "Take at the first tickle in your throat, not later.", s3: "Eight pills every 2-3 hours for 24 hours.", image: img(8) },
  { asin: "B00JM4G1KQ", name: "Plum Flower Jia Wei Xiao Yao Wan", category: "tcm", helps: ["mood", "PMS", "stress"], s1: "Free-and-Easy Wanderer plus mu dan pi and zhi zi for additional heat-clearing.", s2: "Better than the basic xiao yao wan for hot-tempered, easily irritated types.", s3: "Eight pills three times daily.", image: img(9) },
  { asin: "B00FT0LSC6", name: "Plum Flower Suan Zao Ren Tang", category: "tcm", helps: ["sleep", "anxious thoughts"], s1: "Sour jujube seed formula for the mind that won't quiet at night.", s2: "Best for the over-thinker who wakes at 3am and can't get back to sleep.", s3: "Eight pills 30 minutes before bed.", image: img(10) },
  { asin: "B00JM4FWWC", name: "Plum Flower Tian Wang Bu Xin Dan", category: "tcm", helps: ["sleep", "memory", "heart yin"], s1: "Heart-yin tonic for palpitations, restless sleep, and dry-mouth nervous types.", s2: "Especially good for high-strung professionals running on caffeine.", s3: "Eight pills three times daily.", image: img(11) },
  { asin: "B00JM4F0J0", name: "Plum Flower Si Wu Tang", category: "tcm", helps: ["blood tonic", "menstrual support"], s1: "Four-substance decoction; the most-used blood tonic in TCM.", s2: "For pale, fatigued, low-energy types and for menstrual blood deficiency.", s3: "Eight pills three times daily.", image: img(12) },
  { asin: "B00JM4G8FK", name: "Plum Flower Gui Pi Wan", category: "tcm", helps: ["fatigue", "anxiety", "blood and qi"], s1: "Spleen-and-heart support for thinkers who run themselves down.", s2: "Useful for the worrier who can't sleep, eats poorly, and has cold hands.", s3: "Eight pills three times daily.", image: img(13) },
  { asin: "B00JM4FOWO", name: "Plum Flower Bu Zhong Yi Qi Wan", category: "tcm", helps: ["energy", "digestion"], s1: "Center-tonifying classic for low daytime energy and weak digestion.", s2: "Good for the person who feels dragged-down after eating.", s3: "Eight pills three times daily.", image: img(14) },
  { asin: "B00JM4FYK0", name: "Plum Flower Du Huo Ji Sheng Wan", category: "tcm", helps: ["joints", "lower back"], s1: "Classic formula for aching, cold, damp lower back and knees.", s2: "Especially good for older adults and people in damp climates.", s3: "Eight pills three times daily.", image: img(15) },
  { asin: "B07GHZ6CWW", name: "Plum Flower Yu Ping Feng San (Jade Windscreen)", category: "tcm", helps: ["immune", "allergies"], s1: "Jade Windscreen formula for people who catch every cold and have wind-driven allergies.", s2: "Take in autumn for the year ahead, daily through cold-and-flu season.", s3: "Eight pills three times daily.", image: img(16) },
  { asin: "B07GJP4D5W", name: "Plum Flower Liver Bo (Bupleurum & Tang Kuei)", category: "tcm", helps: ["mood", "digestion"], s1: "Bupleurum-tang kuei combination, a softer mover for liver-blood deficiency.", s2: "Good for women with PMS, irritability, and cold extremities.", s3: "Eight pills three times daily.", image: img(17) },
  { asin: "B07J35KK1K", name: "Plum Flower Long Dan Xie Gan Wan", category: "tcm", helps: ["liver-fire", "headache", "irritability"], s1: "Strong liver-fire-clearing formula for headaches, red eyes, and short tempers.", s2: "Use short-term during acute flare-ups, not as daily tonic.", s3: "Eight pills three times daily for up to 2 weeks.", image: img(18) },
  { asin: "B07J34CCKG", name: "Plum Flower Mu Xiang Shun Qi Wan", category: "tcm", helps: ["bloat", "qi stagnation"], s1: "Aucklandia-based formula for bloating, belching, and qi stuck in the middle.", s2: "Useful with stress-driven IBS and post-meal distention.", s3: "Eight pills with meals as needed.", image: img(19) },
  { asin: "B07J35CQXR", name: "Plum Flower Ban Xia Hou Po Tang", category: "tcm", helps: ["throat", "anxiety", "globus"], s1: "For the 'plum-pit throat' sensation of stuck globus from emotional stagnation.", s2: "Especially useful in anxious times when the throat tightens.", s3: "Eight pills three times daily.", image: img(20) },
  { asin: "B07J34GVDH", name: "Plum Flower Sang Ju Yin", category: "tcm", helps: ["early cold", "cough", "wind-heat"], s1: "Mulberry-chrysanthemum formula for the early stages of a wind-heat cold.", s2: "Best when symptoms are mostly upper-respiratory and the throat is dry.", s3: "Eight pills every 3-4 hours at first sign.", image: img(21) },
  { asin: "B07J35JMPB", name: "Plum Flower Sheng Mai San", category: "tcm", helps: ["energy", "heart", "summer-heat"], s1: "Three-herb classic to revive qi after summer-heat or heavy exertion.", s2: "Useful after long workouts or hot summer days.", s3: "Eight pills as needed; safe daily.", image: img(22) },
  { asin: "B07J34DRPL", name: "Plum Flower Ming Mu Di Huang Wan", category: "tcm", helps: ["eyes", "kidney-liver yin"], s1: "Eye-brightening rehmannia formula for tired, dry, screen-fatigued eyes.", s2: "Best for over-40 adults with worsening near vision.", s3: "Eight pills three times daily.", image: img(23) },
  { asin: "B07GHZ7VYV", name: "Plum Flower Er Chen Wan", category: "tcm", helps: ["dampness", "phlegm", "digestion"], s1: "Two-aged-herbs formula for damp-phlegm conditions and sluggish digestion.", s2: "Useful for chronic post-nasal drip and morning brain-fog.", s3: "Eight pills three times daily.", image: img(24) },
  { asin: "B07GJP3T1Q", name: "Plum Flower Ba Zhen Wan (Eight Treasures)", category: "tcm", helps: ["qi and blood", "fatigue"], s1: "Eight-Treasures combines the four-gentlemen and four-substances for a full qi-and-blood tonic.", s2: "Good after a long stretch of overwork, illness, or postpartum.", s3: "Eight pills three times daily for 4-8 weeks.", image: img(25) },
  { asin: "B07J35WG78", name: "Plum Flower Jin Gui Shen Qi Wan", category: "tcm", helps: ["kidney-yang", "lower back", "cold"], s1: "Kidney-yang tonic for cold lower back, fatigue, and frequent urination.", s2: "Especially good for older men and women feeling 'cold from the inside'.", s3: "Eight pills three times daily.", image: img(26) },
  { asin: "B07J35QKZQ", name: "Plum Flower Zuo Gui Wan", category: "tcm", helps: ["kidney-yin", "menopause"], s1: "Restore-the-left kidney-yin tonic for menopausal night sweats and dry skin.", s2: "Companion to liu wei di huang wan but more substantial.", s3: "Eight pills three times daily.", image: img(27) },
  { asin: "B07J34HVR3", name: "Plum Flower You Gui Wan", category: "tcm", helps: ["kidney-yang"], s1: "Restore-the-right kidney-yang tonic for cold, fatigued, low-libido types.", s2: "Stronger than jin gui shen qi wan; not for hot, dry types.", s3: "Eight pills three times daily.", image: img(28) },
  { asin: "B07J34TGSP", name: "Plum Flower Wen Dan Tang", category: "tcm", helps: ["sleep", "anxiety", "heart palpitations"], s1: "Warm-the-gallbladder decoction for the anxious, palpitating, restless type.", s2: "Especially useful when anxiety is paired with reflux or nausea.", s3: "Eight pills three times daily.", image: img(29) },
  { asin: "B07GHZ45VG", name: "Plum Flower Suan Zao Ren Wan (sour jujube)", category: "tcm", helps: ["sleep", "evening anxiety"], s1: "Single-herb sour jujube seed concentrate for evening anxiety and racing mind.", s2: "Lighter and more food-like than valerian.", s3: "Eight pills 30 minutes before bed.", image: img(30) },
  { asin: "B07GJP6FQY", name: "Plum Flower Bao Ying Dan", category: "tcm", helps: ["children", "digestion", "calm"], s1: "Children's formula for upset stomach, restlessness, and teething.", s2: "Used in many Chinese-American households as a household staple.", s3: "Half-dose for children; check with practitioner.", image: img(31) },
  { asin: "B07GHZP2L4", name: "Plum Flower Tao Hong Si Wu Wan", category: "tcm", helps: ["blood circulation", "menstrual"], s1: "Four-substance plus peach-and-safflower for stuck menstrual blood and clots.", s2: "Useful for the woman with painful periods and dark clots.", s3: "Eight pills three times daily during the second half of the cycle.", image: img(32) },
  { asin: "B07J35Y2BK", name: "Plum Flower Wu Ji Bai Feng Wan (White Phoenix)", category: "tcm", helps: ["women", "menstrual", "fatigue"], s1: "Women's tonic combining a black-bone-chicken extract base with classical herbs.", s2: "Used for fatigue, irregular cycles, and post-natal recovery.", s3: "One bottle (10 pills) daily.", image: img(33) },
  { asin: "B07GHZ8R34", name: "Plum Flower Long Yan Rou (longan)", category: "tcm", helps: ["blood tonic", "calm"], s1: "Single-herb longan fruit; sweet, gentle blood tonic.", s2: "Good for tea, soups, or porridges; calming and grounding.", s3: "Five to ten dried fruits in tea, daily.", image: img(34) },
  { asin: "B07GHZ4QH6", name: "Plum Flower Goji Berry Bulk", category: "tcm", helps: ["liver", "eyes", "blood tonic"], s1: "Wolfberry, the daily snack tonic for liver and eye health.", s2: "Eat as snack, throw in oatmeal, or steep in tea.", s3: "Small handful daily.", image: img(35) },
  { asin: "B07J34D7K5", name: "Plum Flower Bai He Gu Jin Wan", category: "tcm", helps: ["lung-yin", "dry cough"], s1: "Lily-bulb formula for dry cough, throat dryness, and lung-yin deficiency.", s2: "Especially useful in dry winters and after viral illness.", s3: "Eight pills three times daily.", image: img(36) },
  { asin: "B07J34Q1FC", name: "Plum Flower Mai Wei Di Huang Wan", category: "tcm", helps: ["lung-yin", "kidney-yin"], s1: "Liu Wei Di Huang Wan plus mai dong and wu wei zi for added lung-yin support.", s2: "Useful for chronic dry cough, post-COVID dryness, and night sweats.", s3: "Eight pills three times daily.", image: img(37) },
  { asin: "B07J35BMH2", name: "Plum Flower Pe Min Kan Wan", category: "tcm", helps: ["allergies", "sinus"], s1: "Modern formula for nasal allergies, sinus congestion, and post-nasal drip.", s2: "Works fast; can be paired with yu ping feng san for prevention.", s3: "Five to eight pills as needed.", image: img(38) },
  { asin: "B07J35DZWC", name: "Plum Flower Bi Yan Pian", category: "tcm", helps: ["sinus", "rhinitis"], s1: "Nose-inflammation tablets for chronic sinus congestion and rhinitis.", s2: "Useful daily during pollen season.", s3: "Four tablets three times daily.", image: img(39) },
  { asin: "B07J34BNKG", name: "Plum Flower Po Sum On Medicated Oil", category: "tcm", helps: ["topical", "muscle ache", "headache"], s1: "Topical herbal oil with menthol and camphor; classic Chinese household remedy.", s2: "Use on temples for tension headaches, on muscles for soreness.", s3: "A few drops, massaged in.", image: img(40) },
  { asin: "B07J35V8XF", name: "Plum Flower White Flower Embrocation Oil", category: "tcm", helps: ["topical", "headache", "congestion"], s1: "Strongly aromatic topical oil; a single drop on temples relieves headache.", s2: "Inhale from the bottle for nasal congestion.", s3: "Use sparingly; very strong.", image: img(41) },
  { asin: "B07J35K7M5", name: "Plum Flower Tiger Balm Red", category: "tcm", helps: ["topical", "muscle"], s1: "Stronger 'red' tiger balm for muscle aches, post-workout soreness, and joint pain.", s2: "Camphor and cassia oil for warming.", s3: "Massage into sore area 2-3 times daily.", image: img(42) },
  { asin: "B07J35NRMJ", name: "Plum Flower Tiger Balm White", category: "tcm", helps: ["topical", "headache"], s1: "Cooler 'white' tiger balm; better for headaches and tension on the upper back.", s2: "Menthol-forward, mild.", s3: "Dab on temples and back of neck.", image: img(43) },
  { asin: "B07J34D1H1", name: "Plum Flower Yunnan Baiyao Capsules", category: "tcm", helps: ["bleeding", "bruises", "trauma"], s1: "Famous Chinese trauma formula; used for bleeding, bruises, and post-surgery recovery.", s2: "Found in many Chinese household first-aid kits.", s3: "Two capsules three times daily for short courses; check practitioner for trauma protocols.", image: img(44) },
  { asin: "B07J35LMY8", name: "Plum Flower Yunnan Baiyao Plaster", category: "tcm", helps: ["topical", "bruises", "joint"], s1: "Adhesive medicated plaster for sprains, strains, and bruises.", s2: "Wear for 8-12 hours, then a rest day before reapplying.", s3: "One plaster per affected area.", image: img(45) },
  { asin: "B07J35QXBT", name: "Plum Flower Salvia Compound Tablets (dan shen)", category: "tcm", helps: ["heart", "circulation"], s1: "Salvia (red sage) compound for heart-blood circulation.", s2: "Used long-term for cardiovascular support, especially with TCM input.", s3: "Three tablets twice daily.", image: img(46) },
  { asin: "B07J35BVL6", name: "Plum Flower Ge Gen Tang", category: "tcm", helps: ["neck stiffness", "common cold"], s1: "Kudzu decoction for neck stiffness from a wind-cold pattern, often the first sign of a cold.", s2: "Take at the first sense of stiffness, before a full cold develops.", s3: "Eight pills every 4 hours for 1-2 days.", image: img(47) },
  { asin: "B07J34PLSP", name: "Plum Flower An Shen Bu Xin Wan", category: "tcm", helps: ["sleep", "calm-the-spirit"], s1: "Calm-the-spirit, nourish-the-heart formula for evening anxiety and insomnia.", s2: "Pairs with suan zao ren tang for stronger sleep support.", s3: "Eight pills 30 minutes before bed.", image: img(48) },
  { asin: "B07J35GZP1", name: "Plum Flower Shou Wu Pian", category: "tcm", helps: ["hair", "blood tonic", "graying"], s1: "Polygonum (he shou wu) tablets used for hair thickness and premature graying.", s2: "Long-game tonic; effects show over months.", s3: "Three tablets twice daily.", image: img(49) },
  { asin: "B07J34T2VC", name: "Plum Flower Long Hu Dieda Wan", category: "tcm", helps: ["trauma", "musculoskeletal"], s1: "Dragon-tiger trauma pills for sports injuries and musculoskeletal recovery.", s2: "Used in martial arts traditions for centuries.", s3: "Eight pills twice daily for 2-3 weeks.", image: img(50) },
  { asin: "B07J35JZWB", name: "Plum Flower Sang Piao Xiao San", category: "tcm", helps: ["bladder", "urinary"], s1: "Mantis-egg-case formula for frequent urination and bladder weakness.", s2: "Used in older adults and after childbirth.", s3: "Eight pills three times daily.", image: img(51) },
  { asin: "B07J34DBXR", name: "Plum Flower Run Chang Wan", category: "tcm", helps: ["constipation", "dryness"], s1: "Moisten-the-intestine pills for dry-type constipation in older adults.", s2: "Gentler than senna; works without dependency.", s3: "Eight pills at bedtime.", image: img(52) },
  { asin: "B07J35JXNQ", name: "Plum Flower Ma Zi Ren Wan", category: "tcm", helps: ["constipation"], s1: "Hemp-seed pills, the most-classical TCM constipation remedy.", s2: "Safe for daily use during dry-stool stretches.", s3: "Eight pills at bedtime.", image: img(53) },
  { asin: "B07J34F71L", name: "Plum Flower Qing Qi Hua Tan Wan", category: "tcm", helps: ["respiratory", "phlegm"], s1: "Clear-qi, transform-phlegm formula for stubborn productive cough with thick phlegm.", s2: "Best in the second half of a cold or in chronic damp-lung conditions.", s3: "Eight pills three times daily.", image: img(54) },
  { asin: "B07J35GHJZ", name: "Plum Flower Jia Wei Da Bu Yin", category: "tcm", helps: ["yin tonic", "menopause"], s1: "Modified great-tonify-the-yin formula for night sweats and bone-marrow heat.", s2: "Used for menopausal hot flashes that don't respond to liu wei di huang wan.", s3: "Eight pills three times daily.", image: img(55) },
  { asin: "B07J34BX8C", name: "Plum Flower Tian Ma Gou Teng Yin", category: "tcm", helps: ["dizziness", "blood pressure", "liver-yang"], s1: "Gastrodia-uncaria formula for liver-yang rising: dizziness, headache, and high blood pressure.", s2: "Pairs well with conventional blood-pressure care.", s3: "Eight pills three times daily.", image: img(56) },
  { asin: "B07J35TNQ6", name: "Plum Flower Bo Zi Yang Xin Wan", category: "tcm", helps: ["sleep", "memory", "heart-spirit"], s1: "Biota-seed nourish-the-heart pills for the forgetful, anxious, restless type.", s2: "Especially useful for older adults losing focus and sleep together.", s3: "Eight pills three times daily.", image: img(57) },

  // ───────────────────────────── EXTRA ADAPTOGENS, WOMEN'S, MEN'S, KIDS, TOPICALS, FOOD-AS-MEDICINE ─────────────────────────────
  { asin: "B0019LRY1S", name: "NOW Foods Eleuthero (Siberian Ginseng) 500mg", category: "herb", helps: ["energy", "endurance", "adaptogen"], s1: "Old-school Soviet research adaptogen for endurance and stress resilience.", s2: "Less stimulating than rhodiola, gentler than panax ginseng.", s3: "Two capsules with breakfast for 6 weeks.", image: img(58) },
  { asin: "B0019LRY2C", name: "NOW Foods American Ginseng 500mg", category: "herb", helps: ["energy", "focus"], s1: "Cooler, calmer cousin to Asian ginseng; classic for mental focus without overstimulation.", s2: "Better for hot, dry, anxious types than the Asian variety.", s3: "Two capsules with breakfast.", image: img(59) },
  { asin: "B07GHZ2RL8", name: "Plum Flower Ren Shen (Asian Ginseng) Tablets", category: "tcm", helps: ["qi tonic", "energy"], s1: "Strong qi tonic for cold, fatigued, low-vitality types.", s2: "Use cautiously in the over-stimulated or hot-tempered.", s3: "Two tablets with breakfast.", image: img(60) },
  { asin: "B0017OBL40", name: "Pukka Herbs Three Ginger Tea", category: "herb", helps: ["digestion", "warming"], s1: "Three-ginger blend for digestion, warming, and circulation.", s2: "A daily after-meal tea that helps stuck digestion move.", s3: "One bag in 8oz hot water after meals.", image: img(61) },
  { asin: "B07PNT9DGC", name: "Pukka Herbs Night Time Tea", category: "herb", helps: ["sleep", "calm"], s1: "Oat flower, chamomile, lavender, and lime flower for an easy bedtime ritual.", s2: "Caffeine-free; safe for nightly use.", s3: "One bag steeped 7 minutes, evening.", image: img(62) },
  { asin: "B07PNT9V8M", name: "Pukka Herbs Womankind Tea", category: "herb", helps: ["women", "hormones"], s1: "Shatavari and rose blend for monthly cycle support.", s2: "Gentle, food-safe, easy to drink daily.", s3: "One bag in 8oz hot water, twice daily.", image: img(63) },
  { asin: "B0019LRY3G", name: "NOW Foods Shatavari 500mg", category: "herb", helps: ["women", "reproductive"], s1: "Ayurvedic women's tonic; the 'hundred husbands' herb.", s2: "Used for fertility support, menopause, and reproductive resilience.", s3: "Two capsules with breakfast.", image: img(64) },
  { asin: "B07YDDYTLR", name: "Banyan Botanicals Women's Natural Transition", category: "herb", helps: ["women", "menopause"], s1: "Ayurvedic blend with shatavari, ashwagandha, and brahmi for menopausal transition.", s2: "Built to ease the body through the change rather than suppress it.", s3: "Two tablets twice daily.", image: img(65) },
  { asin: "B07Z3PB39W", name: "Banyan Botanicals Healthy Hair", category: "herb", helps: ["hair", "skin"], s1: "Bhringaraj-based formula for hair density and scalp health.", s2: "Long-game tonic; use for at least 3-6 months.", s3: "Two tablets twice daily.", image: img(66) },
  { asin: "B07Z3X95SS", name: "Banyan Botanicals Brahmi/Gotu Kola", category: "herb", helps: ["focus", "calm", "skin"], s1: "Ayurvedic brain-calming herb that doubles as a skin-and-circulation tonic.", s2: "Useful for anxious thinkers and people with eczema.", s3: "Two tablets twice daily.", image: img(67) },
  { asin: "B07HKB85GX", name: "Banyan Botanicals Mental Clarity", category: "herb", helps: ["focus", "memory"], s1: "Brahmi-bhringaraj-shankhpushpi blend for cognitive support.", s2: "Vata-pacifying; good for the scattered, anxious thinker.", s3: "Two tablets twice daily.", image: img(68) },
  { asin: "B07HG8QJ8B", name: "Banyan Botanicals Stress Ease", category: "herb", helps: ["stress", "adrenals"], s1: "Ashwagandha plus brahmi, jatamansi, and tulsi for the stressed-out modern adult.", s2: "Calming without making you sleepy.", s3: "Two tablets twice daily.", image: img(69) },
  { asin: "B07Z3MLXVG", name: "Banyan Botanicals I Sleep Soundly", category: "herb", helps: ["sleep"], s1: "Ashwagandha-tagara-jatamansi blend for the racing mind at bedtime.", s2: "Especially good for the anxious sleeper who wakes at 3am.", s3: "Two tablets at bedtime.", image: img(70) },
  { asin: "B07HG7TZG7", name: "Banyan Botanicals Triphala Tablets", category: "herb", helps: ["digestion", "detox", "ayurvedic"], s1: "Tablet form of the three-fruit Ayurvedic classic.", s2: "Daily-use, gentle support for digestion and elimination.", s3: "Two tablets at bedtime.", image: img(71) },
  { asin: "B07HG93FNK", name: "Banyan Botanicals Joint Support", category: "herb", helps: ["joints"], s1: "Boswellia, ashwagandha, and turmeric blend for joint support.", s2: "For aching, stiff, vata-aggravated joints.", s3: "Two tablets twice daily for at least 6 weeks.", image: img(72) },
  { asin: "B0019LRY4Y", name: "NOW Foods Boswellia Extract 500mg", category: "herb", helps: ["joints", "inflammation"], s1: "Frankincense resin extract; well-studied for arthritis and inflammatory bowel.", s2: "Often paired with turmeric for stronger anti-inflammatory effect.", s3: "Two capsules twice daily.", image: img(73) },
  { asin: "B07R5T8X7C", name: "Doctor's Best Triple Magnesium Complex", category: "supplement", helps: ["sleep", "muscle", "calm"], s1: "Three forms of magnesium (glycinate, malate, lysinate) in one capsule.", s2: "Better tolerated than citrate for daily use.", s3: "Two capsules at bedtime.", image: img(74) },
  { asin: "B07JYMG5SK", name: "Doctor's Best Brain Magnesium L-Threonate", category: "supplement", helps: ["memory", "sleep", "brain"], s1: "The only magnesium that crosses the blood-brain barrier in meaningful amounts.", s2: "Most useful for memory, sleep, and age-related cognition.", s3: "Three capsules in the evening.", image: img(75) },
  { asin: "B0019LRY1I", name: "NOW Foods Choline & Inositol 500mg", category: "supplement", helps: ["brain", "liver", "mood"], s1: "Classic combination for brain function, liver health, and mood balance.", s2: "Choline is the underrated nutrient most adults are short on.", s3: "One capsule twice daily.", image: img(76) },
  { asin: "B0019LRY1Y", name: "NOW Foods Acetyl-L-Carnitine 500mg", category: "supplement", helps: ["focus", "energy", "brain"], s1: "Brain-active form of carnitine that supports mitochondrial energy.", s2: "Most-noticed effect is morning mental clarity over 6-8 weeks.", s3: "One capsule before breakfast.", image: img(77) },
  { asin: "B0019LRY2W", name: "NOW Foods Alpha Lipoic Acid 600mg", category: "supplement", helps: ["blood sugar", "antioxidant", "nerves"], s1: "Universal antioxidant that recycles vitamins C and E.", s2: "Useful for blood-sugar control and nerve health.", s3: "One capsule with breakfast on an empty stomach.", image: img(78) },
  { asin: "B0019LRY3W", name: "NOW Foods Berberine 400mg", category: "supplement", helps: ["blood sugar", "cholesterol", "gut"], s1: "Plant alkaloid that lowers blood glucose and rebalances gut bacteria.", s2: "Often called 'nature's metformin' though that's an oversimplification.", s3: "One capsule before each main meal.", image: img(79) },
  { asin: "B0019LRY4E", name: "NOW Foods Cinnamon Bark 600mg", category: "herb", helps: ["blood sugar", "warming"], s1: "Cinnamon extract supports insulin sensitivity and post-meal glucose.", s2: "Ceylon variety has lower coumarin and is safer long-term.", s3: "One capsule with the largest meal.", image: img(80) },
  { asin: "B0019LRY40", name: "NOW Foods Fenugreek 500mg", category: "herb", helps: ["blood sugar", "breastfeeding"], s1: "Ancient herb for blood sugar support and breastfeeding milk supply.", s2: "Adds a maple-syrup-like aroma to sweat; harmless.", s3: "Two capsules with food.", image: img(81) },
  { asin: "B0019LRY46", name: "NOW Foods Bitter Melon Extract 500mg", category: "herb", helps: ["blood sugar"], s1: "Bitter Asian gourd traditionally used for blood-sugar regulation.", s2: "Best stacked with cinnamon and chromium.", s3: "Two capsules with the largest meal.", image: img(82) },
  { asin: "B0019LRY7G", name: "NOW Foods Chromium Picolinate 200mcg", category: "supplement", helps: ["blood sugar", "cravings"], s1: "Trace mineral that improves insulin signaling and lowers sugar cravings.", s2: "Most-noticed effect is fewer 3pm sweet cravings.", s3: "One capsule with breakfast.", image: img(83) },
  { asin: "B07S82BFJB", name: "Garden of Life Sport Recovery (vegan)", category: "supplement", helps: ["recovery", "workout"], s1: "Tart cherry and turmeric post-workout drink for soreness and recovery.", s2: "Useful after long runs, hard lifting, or competition days.", s3: "One scoop within 30 minutes of finishing.", image: img(84) },
  { asin: "B07RGB8RCK", name: "Garden of Life Sport BCAAs (vegan)", category: "supplement", helps: ["workout", "endurance"], s1: "Plant-based branched-chain amino acids for endurance and recovery.", s2: "Useful during long sessions or fasted training.", s3: "One scoop in water during training.", image: img(85) },
  { asin: "B0019LRY54", name: "NOW Foods Beet Root Powder", category: "supplement", helps: ["endurance", "blood pressure", "circulation"], s1: "Whole-beet powder for nitric-oxide-driven endurance and lower blood pressure.", s2: "Most-studied benefit is in 5-10K running times.", s3: "One teaspoon in water 90 minutes before training.", image: img(86) },
  { asin: "B0019LRY5A", name: "NOW Foods Citrulline Powder", category: "supplement", helps: ["endurance", "pump"], s1: "Amino acid that boosts nitric oxide and blood flow during training.", s2: "Most-noticed effect is muscle fullness and reduced fatigue in long sets.", s3: "6g in water, 45 minutes before training.", image: img(87) },
  { asin: "B0019LRY5G", name: "NOW Foods Creatine Monohydrate Powder", category: "supplement", helps: ["strength", "brain", "recovery"], s1: "The most-studied supplement on the planet; works for everyone over time.", s2: "Strength, brain function, and resilience all improve with consistent use.", s3: "5g daily in water, anytime.", image: img(88) },
  { asin: "B0019LRY5M", name: "NOW Foods Sport L-Carnitine Liquid", category: "supplement", helps: ["fat metabolism", "endurance"], s1: "Liquid carnitine for fat-burning support and endurance training.", s2: "Best for long, lower-intensity sessions rather than sprinting.", s3: "One tablespoon 30 minutes before training.", image: img(89) },
  { asin: "B07HW1SF2W", name: "Garden of Life Sport Vegan Pre-Workout", category: "supplement", helps: ["workout", "focus"], s1: "Clean pre-workout with caffeine, beet, and beta-alanine; no artificial sweeteners.", s2: "Mild tingling from beta-alanine is normal.", s3: "One scoop in water 20 minutes before training.", image: img(90) },
  { asin: "B0019LRY60", name: "NOW Foods Liver Refresh", category: "supplement", helps: ["liver", "detox"], s1: "Milk thistle, NAC, and dandelion stack for liver support.", s2: "Especially useful after long stretches of stress, alcohol, or medication.", s3: "Two capsules twice daily for 4 weeks.", image: img(91) },
  { asin: "B0019LRY66", name: "NOW Foods Adam Multivitamin (men)", category: "supplement", helps: ["men", "daily baseline"], s1: "Men's multivitamin without iron, with extra zinc and saw palmetto.", s2: "For active men who want a single-bottle baseline.", s3: "Three softgels with breakfast.", image: img(92) },
  { asin: "B0019LRY6C", name: "NOW Foods Eve Multivitamin (women)", category: "supplement", helps: ["women", "daily baseline"], s1: "Women's multi with iron, biotin, and a hormone-supportive herb blend.", s2: "Better for menstruating women than the men's blend.", s3: "Three softgels with breakfast.", image: img(93) },
  { asin: "B0019LRY6I", name: "NOW Foods Special Two Multivitamin", category: "supplement", helps: ["daily baseline"], s1: "Higher-potency multi for active adults; takes only two tablets a day.", s2: "Includes active B vitamins and chelated minerals.", s3: "Two tablets with breakfast.", image: img(94) },
  { asin: "B07Z3FWMS5", name: "Banyan Botanicals Daily Greens", category: "supplement", helps: ["greens", "daily baseline"], s1: "Ayurvedic-style alkalizing greens powder with moringa, amla, and spirulina.", s2: "Replaces a multivitamin for some people; food-as-medicine approach.", s3: "One teaspoon in water or smoothie daily.", image: img(95) },
  { asin: "B07HJZHV4C", name: "Banyan Botanicals Amla Berry Tablets", category: "herb", helps: ["vitamin C", "antioxidant", "hair"], s1: "Indian gooseberry, the highest natural source of vitamin C.", s2: "Daily-use rasayana for hair, skin, immunity, and longevity.", s3: "Two tablets twice daily.", image: img(96) },
  { asin: "B07HJZ4QPV", name: "Banyan Botanicals Moringa Leaf Tablets", category: "herb", helps: ["greens", "iron", "protein"], s1: "The 'miracle tree' leaf, packed with protein, iron, and a wide micronutrient profile.", s2: "Useful as a daily greens supplement for plant-based eaters.", s3: "Two tablets twice daily.", image: img(97) },
  { asin: "B07HJZWG5Q", name: "Banyan Botanicals Neem Leaf Tablets", category: "herb", helps: ["skin", "detox", "blood"], s1: "Bitter Indian leaf used for skin clarity and blood-cleansing.", s2: "For acne, eczema, and damp-heat skin patterns.", s3: "Two tablets twice daily for short courses (4-8 weeks).", image: img(98) },
  { asin: "B07HJZBJX9", name: "Banyan Botanicals Manjistha Tablets", category: "herb", helps: ["skin", "lymph", "detox"], s1: "Indian madder; classical lymph-mover for skin clarity and tissue cleansing.", s2: "Useful for chronic skin conditions and sluggish lymph.", s3: "Two tablets twice daily.", image: img(99) },
  { asin: "B07HJZD6CK", name: "Banyan Botanicals Guggul Tablets", category: "herb", helps: ["cholesterol", "thyroid", "weight"], s1: "Resin from the guggul tree; classical Ayurvedic for cholesterol and metabolism.", s2: "Most-studied for cholesterol, thyroid, and weight protocols.", s3: "Two tablets twice daily for 8-12 weeks.", image: img(100) },
  { asin: "B07HJZTCYM", name: "Banyan Botanicals Kapha Digest", category: "herb", helps: ["digestion", "sluggish metabolism"], s1: "Pungent-warming digestive blend for the slow-metabolism kapha type.", s2: "Useful before heavy meals or in winter sluggish digestion.", s3: "Two tablets with the largest meal.", image: img(101) },
  { asin: "B07HJZGM5W", name: "Banyan Botanicals Vata Digest", category: "herb", helps: ["digestion", "bloating"], s1: "Warming, grounding digestive for the bloating-prone vata type.", s2: "Reduces gas and helps food move through.", s3: "Two tablets with meals.", image: img(102) },
  { asin: "B07HJZQ86R", name: "Banyan Botanicals Pitta Digest", category: "herb", helps: ["digestion", "reflux"], s1: "Cooling digestive for the high-fire pitta type with reflux or heat-driven IBS.", s2: "Soothes burn without shutting down digestion.", s3: "Two tablets with meals.", image: img(103) },
  { asin: "B07HJZ8M3R", name: "Banyan Botanicals Cardio Comfort", category: "herb", helps: ["heart"], s1: "Arjuna-based heart-support formula from Ayurvedic tradition.", s2: "For long-term cardiovascular resilience, not acute symptoms.", s3: "Two tablets twice daily for 12+ weeks.", image: img(104) },
  { asin: "B07HJZ4G3J", name: "Banyan Botanicals Liver Formula", category: "herb", helps: ["liver", "detox"], s1: "Bhumyamalaki-based liver tonic from Ayurvedic tradition.", s2: "Pairs well with milk thistle for stronger liver protocols.", s3: "Two tablets twice daily.", image: img(105) },
  { asin: "B07HJZRWJX", name: "Banyan Botanicals Kidney Formula", category: "herb", helps: ["kidney", "urinary"], s1: "Punarnava-based formula for kidney and urinary support.", s2: "For mild edema, frequent urination, and lower-back fatigue.", s3: "Two tablets twice daily.", image: img(106) },
  { asin: "B07HJZJWDC", name: "Banyan Botanicals Bone Support", category: "herb", helps: ["bone"], s1: "Plant-based bone-support formula with Ayurvedic herbs and plant calcium.", s2: "Better tolerated than calcium carbonate.", s3: "Two tablets twice daily with food.", image: img(107) },
  { asin: "B07HJZ7WVP", name: "Banyan Botanicals Hingvastak Powder", category: "herb", helps: ["digestion", "gas"], s1: "Asafoetida-based digestive powder; sprinkle on food to prevent gas.", s2: "Especially useful with beans and legume-heavy meals.", s3: "Quarter teaspoon on food before eating.", image: img(108) },
  { asin: "B07HJZBQXT", name: "Banyan Botanicals Sitopaladi Powder", category: "herb", helps: ["cough", "respiratory"], s1: "Sweet Ayurvedic respiratory powder for dry cough and post-illness recovery.", s2: "Safe for kids; tastes mildly sweet.", s3: "Quarter teaspoon mixed with honey twice daily.", image: img(109) },
  { asin: "B07HJZ9PG7", name: "Banyan Botanicals Tulsi Tea Bags", category: "herb", helps: ["stress", "adaptogen"], s1: "Tulsi tea bags for daily adaptogenic support.", s2: "Caffeine-free, easy on the stomach.", s3: "Two cups a day.", image: img(110) },
  { asin: "B07PNT9GHJ", name: "Pukka Herbs Detox Tea", category: "herb", helps: ["liver", "digestion"], s1: "Aniseed, fennel, and cardamom for daily liver and digestion support.", s2: "Light, sweet, easy to drink as a daily ritual.", s3: "One bag in 8oz hot water after the largest meal.", image: img(111) },
  { asin: "B07PNT9JT2", name: "Pukka Herbs Love Tea", category: "herb", helps: ["calm", "heart"], s1: "Rose, chamomile, and lavender for the heart-calming tea ritual.", s2: "A small daily kindness for the anxious.", s3: "One bag in 8oz hot water as needed.", image: img(112) },
  { asin: "B07PNT9XM8", name: "Pukka Herbs After Dinner Tea", category: "herb", helps: ["digestion"], s1: "Fennel, peppermint, and licorice to ease post-meal heaviness.", s2: "A practical tea to keep on the table at dinner.", s3: "One bag steeped 6 minutes after dinner.", image: img(113) },
  { asin: "B07PNT9KQR", name: "Pukka Herbs Mint Matcha Green Tea", category: "herb", helps: ["focus", "antioxidant"], s1: "Matcha-mint blend for clean focus and gentle caffeine.", s2: "Good substitute for coffee on anxious mornings.", s3: "One bag steeped 3 minutes, mid-morning.", image: img(114) },
  { asin: "B07L1JKLR8", name: "Bragg Apple Cider Vinegar Capsules", category: "supplement", helps: ["digestion", "blood sugar"], s1: "ACV in capsule form for those who can't tolerate the liquid taste.", s2: "Same blood-sugar and digestion support, no enamel risk.", s3: "One capsule before each main meal.", image: img(115) },
  { asin: "B0019LRY76", name: "NOW Foods Activated Charcoal", category: "supplement", helps: ["detox", "gas"], s1: "Activated coconut charcoal for occasional gas, bloat, or food poisoning.", s2: "Don't take within 2 hours of medications or other supplements.", s3: "Two capsules with water as needed; not for daily use.", image: img(116) },
  { asin: "B0019LRY7A", name: "NOW Foods Bentonite Clay Powder", category: "supplement", helps: ["detox", "binding"], s1: "Mineral clay used in detox protocols for binding heavy metals and toxins.", s2: "Use with intention and a clinician for serious protocols.", s3: "Half teaspoon in water, away from food and supplements.", image: img(117) },
  { asin: "B07X5DJZS8", name: "Hyland's Calms Forté Sleep Aid", category: "supplement", helps: ["sleep", "calm"], s1: "Homeopathic sleep blend with chamomile, passionflower, and oats.", s2: "Gentle enough for short-term use without next-morning grogginess.", s3: "Two tablets at bedtime.", image: img(118) },
  { asin: "B07RH7HK57", name: "Hyland's Restful Legs Quick-Dissolving Tablets", category: "supplement", helps: ["restless legs"], s1: "Homeopathic remedy for restless legs at night.", s2: "Pairs well with magnesium glycinate for stronger effect.", s3: "Two tablets dissolved under the tongue at bedtime.", image: img(119) },
  { asin: "B07RH75CTJ", name: "Hyland's Bumps 'n Bruises Tablets", category: "supplement", helps: ["bruises", "trauma", "kids"], s1: "Arnica-based homeopathic for bruises, falls, and small trauma.", s2: "Safe for kids; works for adults too.", s3: "Two tablets dissolved under the tongue, three times daily.", image: img(120) },
  { asin: "B07HG7YJSV", name: "Banyan Botanicals Khadi Soap", category: "herb", helps: ["skin", "topical"], s1: "Traditional Indian neem-and-turmeric soap for skin support.", s2: "Gentle daily use; especially good for acne-prone or itchy skin.", s3: "Use as regular bar soap.", image: img(1) },
  { asin: "B07J35WNTR", name: "Plum Flower Plum Dragon Tincture", category: "tcm", helps: ["trauma", "topical"], s1: "Topical liniment for sports injuries, sprains, and bruises.", s2: "Used by martial artists for centuries.", s3: "Apply 2-3 times daily to affected area.", image: img(2) },
  { asin: "B07J34HXMQ", name: "Plum Flower Zheng Gu Shui Liquid", category: "tcm", helps: ["trauma", "topical"], s1: "Bone-setting water; another classic topical for soft-tissue injury.", s2: "Stronger than dit da jow for acute bruising.", s3: "Apply with cotton 2-3 times daily.", image: img(3) },
  { asin: "B07HG8M4LS", name: "Banyan Botanicals Mahanarayan Massage Oil", category: "herb", helps: ["joints", "topical"], s1: "Sesame-based Ayurvedic oil with 28 herbs for joint and muscle massage.", s2: "Daily self-massage with this oil supports joint mobility long-term.", s3: "Warm and massage into joints before bath.", image: img(4) },
  { asin: "B07HG7M5JV", name: "Banyan Botanicals Sesame Oil (cured)", category: "herb", helps: ["skin", "daily oil massage"], s1: "Cured organic sesame oil for daily abhyanga (Ayurvedic self-massage).", s2: "Most foundational Ayurvedic practice for nervous system grounding.", s3: "Warm and massage onto skin before bath, 15 minutes a day.", image: img(5) },
  { asin: "B07HG83KVR", name: "Banyan Botanicals Coconut Oil (organic)", category: "herb", helps: ["skin", "oil pulling"], s1: "Organic coconut oil for cooking, oil pulling, and pitta-pacifying massage.", s2: "Cooler than sesame; better in summer and for hot-running types.", s3: "One tablespoon for oil pulling first thing in the morning.", image: img(6) },
  { asin: "B0019LRY7M", name: "NOW Foods Castor Oil", category: "supplement", helps: ["skin", "hair", "compress"], s1: "Cold-pressed castor oil for hair, brows, and abdominal castor-oil packs.", s2: "Castor packs over the liver and lower abdomen support gentle detox.", s3: "Apply on cotton flannel as a 30-minute pack 2-3x weekly.", image: img(7) },
  { asin: "B0019LRY7S", name: "NOW Foods Black Cumin Seed Oil", category: "supplement", helps: ["immune", "allergies"], s1: "Nigella sativa oil; well-studied for allergies and immune resilience.", s2: "Take orally; some apply topically for skin support.", s3: "One teaspoon daily before breakfast.", image: img(8) },
  { asin: "B0019LRY80", name: "NOW Foods Evening Primrose Oil", category: "supplement", helps: ["women", "skin", "GLA"], s1: "Source of GLA, an essential fatty acid for hormonal balance and skin.", s2: "Especially useful for PMS and dry skin.", s3: "One softgel three times daily.", image: img(9) },
  { asin: "B0019LRY8G", name: "NOW Foods Borage Oil", category: "supplement", helps: ["skin", "GLA", "inflammation"], s1: "Stronger source of GLA than evening primrose oil.", s2: "Better for chronic eczema and stubborn dry skin.", s3: "One softgel daily with food.", image: img(10) },
  { asin: "B0019LRY8M", name: "NOW Foods Flaxseed Oil 1000mg", category: "supplement", helps: ["omega-3", "skin"], s1: "Plant-based ALA omega-3 from flaxseed; backup to algae omega for everyday use.", s2: "Conversion to EPA/DHA is limited; not a full substitute for algae oil.", s3: "Two softgels with breakfast.", image: img(11) },
  { asin: "B0019LRY8S", name: "NOW Foods Hemp Seed Oil 1000mg", category: "supplement", helps: ["omega-3", "omega-6 balance"], s1: "Hemp oil with a balanced omega-3 to omega-6 ratio.", s2: "Supports skin and hormonal balance.", s3: "Two softgels with food.", image: img(12) },
  { asin: "B0019LRY8Y", name: "NOW Foods Pumpkin Seed Oil", category: "supplement", helps: ["prostate", "bladder", "hair"], s1: "Pumpkin seed oil for prostate, bladder, and hair-loss support.", s2: "Useful for older men and women with bladder weakness.", s3: "One softgel with each main meal.", image: img(13) },
  { asin: "B0019LRY94", name: "NOW Foods Sea Buckthorn Oil", category: "supplement", helps: ["skin", "mucous membranes"], s1: "Bright orange berry oil for dry mucous membranes and aging skin.", s2: "Especially useful for menopausal vaginal dryness and dry eyes.", s3: "One softgel daily with food.", image: img(14) },
];

const CATS = [
  { id: "all", label: `All (${PICKS.length})` },
  { id: "supplement", label: "Supplements" },
  { id: "herb", label: "Western herbs" },
  { id: "tcm", label: "Chinese (TCM)" },
];

function amazonHref(asin: string) {
  return `https://www.amazon.com/dp/${asin}/?tag=spankyspinola-20`;
}

export default function Supplements() {
  const [filter, setFilter] = useState<string>("all");
  const [query, setQuery] = useState("");

  const filtered = useMemo(() => {
    let list = PICKS;
    if (filter !== "all") list = list.filter((p) => p.category === filter);
    if (query.trim()) {
      const q = query.toLowerCase();
      list = list.filter(
        (p) =>
          p.name.toLowerCase().includes(q) ||
          p.s1.toLowerCase().includes(q) ||
          p.s2.toLowerCase().includes(q) ||
          p.s3.toLowerCase().includes(q) ||
          p.helps.some((h) => h.toLowerCase().includes(q)),
      );
    }
    return list;
  }, [filter, query]);

  const counts = useMemo(() => {
    const c = { supplement: 0, herb: 0, tcm: 0 };
    PICKS.forEach((p) => { c[p.category] += 1; });
    return c;
  }, []);

  return (
    <div className="container py-12">
      <header className="max-w-3xl">
        <span className="inline-flex items-center gap-2 text-xs uppercase tracking-[0.2em] text-foreground/65">
          <Sparkles className="h-3.5 w-3.5 text-primary" /> Curated, plant-relevant
        </span>
        <h1 className="font-serif text-4xl mt-2">
          Supplements, herbs &amp; TCM that actually help
        </h1>
        <p className="mt-3 text-lg text-foreground/75 leading-relaxed">
          {PICKS.length} verified picks across vegan-relevant supplements ({counts.supplement}),
          western herbs ({counts.herb}), and traditional Chinese formulas ({counts.tcm}).
          Each entry is three plain sentences: what it is, who it helps, how to use it.
          Every Amazon link is marked &quot;(paid link)&quot; and supports this site
          at no cost to you. None of this replaces a clinician — it is curation, not prescription.
        </p>
      </header>

      <div className="mt-8 flex flex-col md:flex-row gap-3 md:items-center md:justify-between">
        <div className="inline-flex flex-wrap gap-2">
          {CATS.map((c) => (
            <button
              key={c.id}
              onClick={() => setFilter(c.id)}
              className={
                "rounded-full px-4 py-2 text-sm border transition-colors " +
                (filter === c.id
                  ? "bg-primary text-primary-foreground border-primary"
                  : "bg-background text-foreground/75 border-border hover:bg-primary/5")
              }
            >
              {c.label}
            </button>
          ))}
        </div>
        <label className="inline-flex items-center gap-2 rounded-full border border-border bg-background px-4 py-2">
          <Search className="h-4 w-4 text-foreground/60" />
          <input
            value={query}
            onChange={(e) => setQuery(e.target.value)}
            placeholder="Search by name, herb, or symptom"
            className="bg-transparent outline-none text-sm w-full md:w-64"
          />
        </label>
      </div>

      <p className="mt-4 text-xs text-foreground/55">Showing {filtered.length} of {PICKS.length}.</p>

      <ul className="mt-6 grid sm:grid-cols-2 lg:grid-cols-3 gap-5">
        {filtered.map((p) => (
          <li
            key={p.asin}
            className="rounded-2xl border border-border bg-card overflow-hidden flex flex-col pc-shadow"
          >
            <div className="aspect-[16/10] bg-secondary/30 overflow-hidden">
              <img
                src={p.image}
                alt={p.name}
                loading="lazy"
                className="w-full h-full object-cover"
              />
            </div>
            <div className="p-5 flex flex-col flex-1">
              <p className="text-xs uppercase tracking-wide text-secondary-foreground/80">
                {p.category === "supplement"
                  ? "Supplement"
                  : p.category === "herb"
                    ? "Western herb"
                    : "Traditional Chinese"}
              </p>
              <h3 className="font-serif text-base mt-1 leading-snug">{p.name}</h3>
              <p className="text-sm text-foreground/80 mt-3 leading-relaxed">{p.s1}</p>
              <p className="text-sm text-foreground/75 mt-2 leading-relaxed">{p.s2}</p>
              <p className="text-sm text-foreground/75 mt-2 leading-relaxed">{p.s3}</p>
              <ul className="mt-4 flex flex-wrap gap-1.5">
                {p.helps.map((h) => (
                  <li
                    key={h}
                    className="text-[11px] uppercase tracking-wide rounded-full bg-primary/10 text-primary px-2 py-0.5"
                  >
                    {h}
                  </li>
                ))}
              </ul>
              <a
                href={amazonHref(p.asin)}
                rel="nofollow sponsored noopener"
                target="_blank"
                className="mt-5 inline-flex items-center gap-1.5 text-primary text-sm font-medium underline self-start"
              >
                See on Amazon (paid link) <ExternalLink className="h-3.5 w-3.5" />
              </a>
            </div>
          </li>
        ))}
      </ul>

      <p className="mt-12 text-xs text-foreground/55 max-w-3xl">
        Editorial note: this curation is independent. Affiliate links cost you
        nothing extra. Talk to your clinician about anything you take, especially
        if you are pregnant, on medications, or planning surgery. Some herbs
        interact with prescription drugs.
      </p>
    </div>
  );
}
